name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build the application
        run: ci/build-app.sh
      - name: Test the application
        run: ci/unit-test-app.sh
      - uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true
  Linting:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true
      - name: Run the linter
        uses: super-linter/super-linter/slim@latest
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true  
    
    
