name: Main workflow
on: push
env: # Set the secret as an input
  docker_username: ${{ lowercase(github.actor) }} 
  docker_password: ${{ secrets.GITHUB_TOKEN }} # Nees to be set to be made available to the workflowA
  GIT_COMMIT: ${{ github.sha }} 
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Build the application
        run: ci/build-app.sh
      - name: Test the application
        run: ci/unit-test-app.sh
      - uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true
  Linting:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
      - name: Run the linter
        uses: super-linter/super-linter/slim@latest
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
  Docker:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download source code
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
      - name: Build the container
        run: bash ci/build-docker.sh
      - name: Push container
        run: bash ci/push-docker.sh
  ComponentTest:
    runs-on: ubuntu-latest
    needs: [Docker]
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Execute component test
        run: bash ci/component-test.sh
  PerformanceTest:
    runs-on: ubuntu-latest
    needs: [Docker]
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Execute perfromance test
        run: bash ci/performance-test.sh
